### ISSUE TITLE
Timestamp of events is at the start of the defined time period

### ISSUE THREAD

**Issue by TimShaw61** [airbus-cyber/graylog-plugin-aggregation-count#24]
v2.2 (Because I'm still running graylog 3.3x)
![Screenshot from 2022-03-08 17-48-18](https://user-images.githubusercontent.com/17780891/157295946-d1b77ba0-c49a-43cd-8629-b4937113a7b5.png)

When creating an event definition and a "search within the last " setting of, say, 1 hour is defined then any resulting event triggered by the definition will have its timestamp as the beginning of that aggregation time range and not the time that the event was created

This seem wrong to me...the event pictured was actually created by the system at 16:57...

**Comment by frantz45** [comment]
You are right, with Graylog builtin "Filter  & Aggregation" the Event's Timestamp is the end of the aggregation period plus 1 millisecond. 

![builtin_behavior](https://yourimageshare.com/ib/elVOTbJhoT.webp)

However I think we won't fix this because this plugin is not maintained anymore.
Indeed Graylog builtin features now allow to use aggregation in an event definition (it wasn't the case some years ago that's why we created this plugin).
The most recent release v4.1.1 is the last.
