### ISSUE TITLE
Aggregation table in notification

### ISSUE THREAD

**Issue by QuaiGoner** [airbus-cyber/graylog-plugin-aggregation-count#27]
Hello! Is that possible to create notification like this using this plugin? 
![image](https://user-images.githubusercontent.com/41058180/180360367-c5439ffb-5353-4eff-a1f9-605bd6b674b7.png)

**Comment by frantz45** [comment]
Hello,
Firstly this plugin has only be tested with the notification type "Logging Alert" (https://github.com/airbus-cyber/graylog-plugin-logging-alert). I'm not sure about its behavior with other notification types.
Secondly I don't think your use case is possible because this plugin will trigger one notification per "aggregation field", you can't have multiple "aggregation fields" in one notification. With your example you would have 4 notifications: edit, show, index, login.
Finally you need to know this plugin will not be maintained anymore, because Graylog builtin features now allow to use aggregation in an event definition (it wasn't the case some years ago that's why we created this plugin). The most recent release v4.1.1 is the last.
